import type { Metadata } from "next";
import { Space_Grotesk as SpaceGrotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = SpaceGrotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{ children: React.ReactNode }>;

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        { children }
      </body>
    </html>
  );
};

export default RootLayout;
